export interface LocationData {
  slug: string;
  city: string;
  county: string;
  state: string;
  population?: string;
  description: string;
  industries: string[];
  keywords: string[];
}

export const UTAH_LOCATIONS: LocationData[] = [
  {
    slug: "salt-lake-city",
    city: "Salt Lake City",
    county: "Salt Lake",
    state: "Utah",
    population: "200,000+",
    description: "Utah's capital and largest city, home to a diverse mix of restaurants, retail, healthcare, and professional services businesses.",
    industries: ["Restaurants", "Retail", "Medical", "Professional Services", "Hotels"],
    keywords: ["merchant services Salt Lake City", "credit card processing Salt Lake City", "POS systems Salt Lake City", "payment processing SLC"],
  },
  {
    slug: "provo",
    city: "Provo",
    county: "Utah",
    state: "Utah",
    population: "115,000+",
    description: "Utah County's largest city and a growing hub for tech startups, restaurants, retail, and service businesses.",
    industries: ["Restaurants", "Retail", "Tech", "Professional Services", "Salons & Spas"],
    keywords: ["merchant services Provo", "credit card processing Provo Utah", "POS systems Provo", "payment processing Utah County"],
  },
  {
    slug: "orem",
    city: "Orem",
    county: "Utah",
    state: "Utah",
    population: "98,000+",
    description: "A thriving retail and service corridor in Utah County with a high concentration of restaurants, shops, and medical practices.",
    industries: ["Retail", "Restaurants", "Medical", "Automotive", "Salons & Spas"],
    keywords: ["merchant services Orem", "credit card processing Orem Utah", "POS systems Orem", "payment processing Orem"],
  },
  {
    slug: "lehi",
    city: "Lehi",
    county: "Utah",
    state: "Utah",
    population: "75,000+",
    description: "One of Utah's fastest-growing cities, anchored by Silicon Slopes tech companies and a booming retail and restaurant scene.",
    industries: ["Tech", "Restaurants", "Retail", "Professional Services"],
    keywords: ["merchant services Lehi", "credit card processing Lehi Utah", "POS systems Lehi", "payment processing Silicon Slopes"],
  },
  {
    slug: "american-fork",
    city: "American Fork",
    county: "Utah",
    state: "Utah",
    population: "35,000+",
    description: "A growing Utah County city with a strong mix of local restaurants, retail shops, and service businesses.",
    industries: ["Restaurants", "Retail", "Professional Services", "Automotive"],
    keywords: ["merchant services American Fork", "credit card processing American Fork", "POS systems American Fork Utah"],
  },
  {
    slug: "draper",
    city: "Draper",
    county: "Salt Lake",
    state: "Utah",
    population: "50,000+",
    description: "A premier South Valley community with upscale retail, restaurants, medical offices, and professional services.",
    industries: ["Retail", "Restaurants", "Medical", "Professional Services"],
    keywords: ["merchant services Draper", "credit card processing Draper Utah", "POS systems Draper", "payment processing Draper"],
  },
  {
    slug: "south-jordan",
    city: "South Jordan",
    county: "Salt Lake",
    state: "Utah",
    population: "75,000+",
    description: "A rapidly growing South Valley city with Daybreak and a strong base of retail, restaurants, and professional services.",
    industries: ["Retail", "Restaurants", "Medical", "Professional Services"],
    keywords: ["merchant services South Jordan", "credit card processing South Jordan Utah", "POS systems South Jordan"],
  },
  {
    slug: "west-jordan",
    city: "West Jordan",
    county: "Salt Lake",
    state: "Utah",
    population: "115,000+",
    description: "One of Utah's largest cities with a diverse business community spanning retail, restaurants, automotive, and services.",
    industries: ["Retail", "Restaurants", "Automotive", "Professional Services"],
    keywords: ["merchant services West Jordan", "credit card processing West Jordan Utah", "POS systems West Jordan"],
  },
  {
    slug: "sandy",
    city: "Sandy",
    county: "Salt Lake",
    state: "Utah",
    population: "95,000+",
    description: "A major South Valley hub with high-traffic retail corridors, restaurants, and a growing medical and professional services sector.",
    industries: ["Retail", "Restaurants", "Medical", "Automotive"],
    keywords: ["merchant services Sandy Utah", "credit card processing Sandy", "POS systems Sandy Utah"],
  },
  {
    slug: "murray",
    city: "Murray",
    county: "Salt Lake",
    state: "Utah",
    population: "50,000+",
    description: "Centrally located in the Salt Lake Valley with a dense concentration of retail, restaurants, and medical businesses.",
    industries: ["Retail", "Restaurants", "Medical", "Automotive"],
    keywords: ["merchant services Murray Utah", "credit card processing Murray", "POS systems Murray Utah"],
  },
  {
    slug: "layton",
    city: "Layton",
    county: "Davis",
    state: "Utah",
    population: "80,000+",
    description: "Davis County's largest city and a major retail and restaurant destination for Northern Utah businesses.",
    industries: ["Retail", "Restaurants", "Automotive", "Professional Services"],
    keywords: ["merchant services Layton Utah", "credit card processing Layton", "POS systems Layton Utah", "payment processing Davis County"],
  },
  {
    slug: "bountiful",
    city: "Bountiful",
    county: "Davis",
    state: "Utah",
    population: "45,000+",
    description: "A well-established Davis County community with a strong local business community in retail, restaurants, and services.",
    industries: ["Retail", "Restaurants", "Medical", "Professional Services"],
    keywords: ["merchant services Bountiful Utah", "credit card processing Bountiful", "POS systems Bountiful Utah"],
  },
  {
    slug: "ogden",
    city: "Ogden",
    county: "Weber",
    state: "Utah",
    population: "87,000+",
    description: "Weber County's largest city with a revitalized downtown, diverse restaurant scene, and growing retail and service sectors.",
    industries: ["Restaurants", "Retail", "Automotive", "Professional Services"],
    keywords: ["merchant services Ogden Utah", "credit card processing Ogden", "POS systems Ogden Utah", "payment processing Weber County"],
  },
  {
    slug: "springville",
    city: "Springville",
    county: "Utah",
    state: "Utah",
    population: "35,000+",
    description: "A growing Utah County city known for its arts community, local restaurants, and expanding retail and service businesses.",
    industries: ["Restaurants", "Retail", "Professional Services", "Salons & Spas"],
    keywords: ["merchant services Springville Utah", "credit card processing Springville", "POS systems Springville Utah"],
  },
  {
    slug: "spanish-fork",
    city: "Spanish Fork",
    county: "Utah",
    state: "Utah",
    population: "42,000+",
    description: "A fast-growing Utah County city with a strong local business community in restaurants, retail, and automotive services.",
    industries: ["Restaurants", "Retail", "Automotive", "Professional Services"],
    keywords: ["merchant services Spanish Fork Utah", "credit card processing Spanish Fork", "POS systems Spanish Fork Utah"],
  },
  {
    slug: "park-city",
    city: "Park City",
    county: "Summit",
    state: "Utah",
    population: "8,000+",
    description: "Utah's premier mountain resort town with a high concentration of upscale restaurants, retail boutiques, and hospitality businesses.",
    industries: ["Restaurants", "Retail", "Hospitality", "Professional Services"],
    keywords: ["merchant services Park City Utah", "credit card processing Park City", "POS systems Park City Utah", "restaurant POS Park City"],
  },
  {
    slug: "heber-city",
    city: "Heber City",
    county: "Wasatch",
    state: "Utah",
    population: "16,000+",
    description: "Wasatch County's growing hub with a mix of local restaurants, retail, and service businesses serving both residents and visitors.",
    industries: ["Restaurants", "Retail", "Professional Services", "Automotive"],
    keywords: ["merchant services Heber City Utah", "credit card processing Heber City", "POS systems Heber City Utah"],
  },
];

export function getLocationBySlug(slug: string): LocationData | undefined {
  return UTAH_LOCATIONS.find((l) => l.slug === slug);
}
